/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x2.npy /localscratch/rps/plane_x2.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x3.npy /localscratch/rps/plane_x3.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x5.npy /localscratch/rps/plane_x5.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x6.npy /localscratch/rps/plane_x6.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x8.npy /localscratch/rps/plane_x8.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x9.npy /localscratch/rps/plane_x9.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x11.npy /localscratch/rps/plane_x11.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x12.npy /localscratch/rps/plane_x12.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x14.npy /localscratch/rps/plane_x14.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x15.npy /localscratch/rps/plane_x15.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x17.npy /localscratch/rps/plane_x17.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x18.npy /localscratch/rps/plane_x18.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x20.npy /localscratch/rps/plane_x20.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x21.npy /localscratch/rps/plane_x21.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x23.npy /localscratch/rps/plane_x23.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x24.npy /localscratch/rps/plane_x24.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x26.npy /localscratch/rps/plane_x26.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x27.npy /localscratch/rps/plane_x27.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x29.npy /localscratch/rps/plane_x29.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x30.npy /localscratch/rps/plane_x30.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x32.npy /localscratch/rps/plane_x32.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x33.npy /localscratch/rps/plane_x33.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x35.npy /localscratch/rps/plane_x35.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x36.npy /localscratch/rps/plane_x36.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /localscratch/merge/plane_x38.npy /localscratch/rps/plane_x38.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x39.npy /localscratch/rps/plane_x39.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x41.npy /localscratch/rps/plane_x41.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x42.npy /localscratch/rps/plane_x42.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x44.npy /localscratch/rps/plane_x44.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x45.npy /localscratch/rps/plane_x45.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x47.npy /localscratch/rps/plane_x47.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x48.npy /localscratch/rps/plane_x48.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x50.npy /localscratch/rps/plane_x50.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x51.npy /localscratch/rps/plane_x51.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x53.npy /localscratch/rps/plane_x53.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x54.npy /localscratch/rps/plane_x54.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x56.npy /localscratch/rps/plane_x56.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x57.npy /localscratch/rps/plane_x57.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x59.npy /localscratch/rps/plane_x59.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x60.npy /localscratch/rps/plane_x60.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x62.npy /localscratch/rps/plane_x62.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x63.npy /localscratch/rps/plane_x63.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x65.npy /localscratch/rps/plane_x65.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x66.npy /localscratch/rps/plane_x66.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x68.npy /localscratch/rps/plane_x68.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x69.npy /localscratch/rps/plane_x69.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x70.npy /localscratch/rps/plane_x70.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x71.npy /localscratch/rps/plane_x71.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x72.npy /localscratch/rps/plane_x72.npy
/opt/anaconda2/envs/powerAIlab/bin/ipython get_region_props.py /media/data/merge/plane_x75.npy /localscratch/rps/plane_x75.npy
