image { 
  hdf5: "/media/data_cifs/connectomics/datasets/third_party/wide_fov/berson8/train/grayscale_maps.h5:raw" 
}image_mean: 154
image_stddev: 33
seed_policy: "PolicyPeaks" 
model_checkpoint_path: "/media/data_cifs/connectomics/ffn_ckpts/wide_fov/convstack_3d_shallow_allbutberson_r0/model.ckpt-124255" 
model_name: "convstack_3d_shallow.ConvStack3DFFNModel" 
model_args: "{\"depth\": 12, \"fov_size\": [57, 57, 13], \"deltas\": [8, 8, 3]}" 
segmentation_output_dir: "/media/data_cifs/connectomics/ffn_inferred/wide_fov/convstack_3d_shallow_allbutberson_r0_topup_124255/berson8/train" 
inference_options { 
  init_activation: 0.95 
  pad_value: 0.05 
  move_threshold: 0.8 
  min_boundary_dist { x: 1 y: 1 z: 1} 
  segment_threshold: 0.6 
  min_segment_size: 1000 
} 
